apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus_scraper:9090
    isDefault: true
    editable: false

  - name: QuestDB
    type: postgres
    access: proxy
    url: questdb_timeseries:8812
    database: qdb
    user: admin
    secureJsonData:
      password: quest
    editable: false
